import type { DisplayKind } from "./types.ts";

export const englishLabels: Readonly<
  Record<DisplayKind, Readonly<Record<string, string>>>
> = Object.freeze({
  element: Object.freeze({
    Aerogel: "Aerogel",
    Algae: "Algae",
    Aluminum: "Aluminum",
    AluminumGas: "Aluminum Gas",
    AluminumOre: "Aluminum Ore",
    Amber: "Amber",
    Basalt: "Basalt",
    Bitumen: "Bitumen",
    BleachStone: "Bleach Stone",
    Brick: "Brick",
    Brine: "Brine",
    BrineIce: "Brine Ice",
    COMPOSITION: "Composition",
    Carbon: "Coal",
    CarbonDioxide: "Carbon Dioxide",
    CarbonFibre: "Carbon Fiber",
    CarbonGas: "Carbon Gas",
    Cement: "Cement",
    CementMix: "Cement Mix",
    Ceramic: "Ceramic",
    Chlorine: "Liquid Chlorine",
    ChlorineGas: "Chlorine Gas",
    Cinnabar: "Cinnabar Ore",
    Clay: "Clay",
    Cobalt: "Cobalt",
    CobaltGas: "Cobalt Gas",
    Cobaltite: "Cobalt Ore",
    ContaminatedOxygen: "Polluted Oxygen",
    Copper: "Copper",
    CopperGas: "Copper Gas",
    Coquina: "Coquina",
    Corallium: "Corallium",
    Corium: "Corium",
    Creature: "Genetic Ooze",
    CrudeOil: "Crude Oil",
    CrushedIce: "Crushed Ice",
    CrushedRock: "Crushed Rock",
    Cuprite: "Copper Ore",
    DepletedUranium: "Depleted Uranium",
    Diamond: "Diamond",
    Dirt: "Dirt",
    DirtyIce: "Polluted Ice",
    DirtyWater: "Polluted Water",
    Electrum: "Electrum",
    EnrichedUranium: "Enriched Uranium",
    Ethanol: "Ethanol",
    EthanolGas: "Ethanol Gas",
    FabricatedWood: "Plywood",
    Fallout: "Nuclear Fallout",
    Fertilizer: "Fertilizer",
    FishMilk: "Ovolene",
    FishMilkIce: "Frozen Ovolene",
    FoolsGold: "Pyrite",
    Fossil: "Fossil",
    FrozenInk: "Frozen Squid Ink",
    FrozenPhytoOil: "Frozen Phyto Oil",
    Fullerene: "Fullerene",
    Galena: "Galena",
    Glass: "Glass",
    Gold: "Gold",
    GoldAmalgam: "Gold Amalgam",
    GoldGas: "Gold Gas",
    Granite: "Granite",
    Graphite: "Graphite",
    Gunk: "Solid Gunk",
    HardPolypropylene: "Plastium",
    Helium: "Helium",
    Hydrogen: "Hydrogen Gas",
    Ice: "Ice",
    IgneousRock: "Igneous Rock",
    Ink: "Squid Ink",
    Iridium: "Iridium",
    IridiumGas: "Iridium Gas",
    Iron: "Iron",
    IronGas: "Iron Gas",
    IronOre: "Iron Ore",
    Isoresin: "Isosap",
    Katairite: "Abyssalite",
    Latex: "Latex",
    Lead: "Lead",
    LeadGas: "Lead Gas",
    Lime: "Lime",
    LiquidCarbonDioxide: "Liquid Carbon Dioxide",
    LiquidGunk: "Gunk",
    LiquidHelium: "Helium",
    LiquidHydrogen: "Liquid Hydrogen",
    LiquidMethane: "Liquid Methane",
    LiquidOxygen: "Liquid Oxygen",
    LiquidPhosphorus: "Liquid Phosphorus",
    LiquidPropane: "Liquid Propane",
    LiquidSulfur: "Liquid Sulfur",
    MaficRock: "Mafic Rock",
    Magma: "Magma",
    Mercury: "Mercury",
    MercuryGas: "Mercury Gas",
    Methane: "Natural Gas",
    Milk: "Brackene",
    MilkFat: "Brackwax",
    MilkIce: "Frozen Brackene",
    MoltenAluminum: "Molten Aluminum",
    MoltenCarbon: "Liquid Carbon",
    MoltenCobalt: "Molten Cobalt",
    MoltenCopper: "Molten Copper",
    MoltenGlass: "Molten Glass",
    MoltenGold: "Molten Gold",
    MoltenIridium: "Molten Iridium",
    MoltenIron: "Molten Iron",
    MoltenLead: "Molten Lead",
    MoltenNickel: "Molten Nickel",
    MoltenNiobium: "Molten Niobium",
    MoltenSalt: "Molten Salt",
    MoltenSteel: "Molten Steel",
    MoltenSucrose: "Liquid Sucrose",
    MoltenSyngas: "Molten Synthesis Gas",
    MoltenTungsten: "Molten Tungsten",
    MoltenUranium: "Liquid Uranium",
    MoltenZinc: "Molten Zinc",
    Mucus: "Mucin",
    Mud: "Mud",
    MurkyBrine: "Polluted Brine",
    MurkyBrineIce: "Polluted Brine Ice",
    Naphtha: "Liquid Naphtha",
    NaturalResin: "Resin",
    NaturalSolidResin: "Solid Resin",
    Nickel: "Nickel",
    NickelGas: "Nickel Gas",
    NickelOre: "Nickel Ore",
    Niobium: "Niobium",
    NiobiumGas: "Niobium Gas",
    NuclearWaste: "Liquid Nuclear Waste",
    Obsidian: "Obsidian",
    OxyRock: "Oxylite",
    Oxygen: "Oxygen",
    PalmWood: "Gum Wood",
    Pearl: "Pearl",
    Peat: "Peat",
    Petroleum: "Petroleum",
    PhosphateNodules: "Phosphate Nodules",
    Phosphorite: "Phosphorite",
    Phosphorus: "Refined Phosphorus",
    PhosphorusGas: "Phosphorus Gas",
    PhytoOil: "Phyto Oil",
    Polypropylene: "Plastic",
    Propane: "Propane Gas",
    Radium: "Radium",
    RefinedCarbon: "Refined Carbon",
    RefinedLipid: "Biodiesel",
    Regolith: "Regolith",
    Resin: "Sap",
    RockGas: "Rock Gas",
    Rubber: "Rubber",
    Rust: "Rust",
    Salt: "Salt",
    SaltGas: "Salt Gas",
    SaltWater: "Salt Water",
    Sand: "Sand",
    SandCement: "Sand Cement",
    SandStone: "Sandstone",
    SedimentaryRock: "Sedimentary Rock",
    Shale: "Shale",
    SiltStone: "Siltstone",
    Slabs: "Building Slab",
    SlimeMold: "Slime",
    Snow: "Snow",
    SolidCarbonDioxide: "Solid Carbon Dioxide",
    SolidChlorine: "Solid Chlorine",
    SolidCrudeOil: "Solid Crude Oil",
    SolidEthanol: "Solid Ethanol",
    SolidHydrogen: "Solid Hydrogen",
    SolidMercury: "Mercury",
    SolidMethane: "Solid Methane",
    SolidMucus: "Frozen Mucin",
    SolidNaphtha: "Solid Naphtha",
    SolidNuclearWaste: "Solid Nuclear Waste",
    SolidOxygen: "Solid Oxygen",
    SolidPetroleum: "Solid Petroleum",
    SolidPropane: "Solid Propane",
    SolidResin: "Solid Sap",
    SolidSuperCoolant: "Solid Super Coolant",
    SolidSyngas: "Solid Synthesis Gas",
    SolidViscoGel: "Solid Visco-Gel",
    SourGas: "Sour Gas",
    StableSnow: "Packed Snow",
    Steam: "Steam",
    Steel: "Steel",
    SteelGas: "Steel Gas",
    Sucrose: "Sucrose",
    SugarWater: "Nectar",
    Sulfur: "Sulfur",
    SulfurGas: "Sulfur Gas",
    SuperCoolant: "Super Coolant",
    SuperCoolantGas: "Super Coolant Gas",
    SuperInsulator: "Insulite",
    Syngas: "Synthesis Gas",
    Tallow: "Tallow",
    TempConductorSolid: "Thermium",
    ToxicMud: "Polluted Mud",
    ToxicSand: "Polluted Dirt",
    Tungsten: "Tungsten",
    TungstenGas: "Tungsten Gas",
    Unobtanium: "Neutronium",
    UraniumOre: "Uranium Ore",
    Vacuum: "Vacuum",
    ViscoGel: "Visco-Gel Fluid",
    Void: "Void",
    Water: "Water",
    Wolframite: "Wolframite",
    WoodLog: "Wood",
    Yellowcake: "Yellowcake",
    Zinc: "Zinc",
    ZincGas: "Zinc Gas",
    ZincOre: "Zinc Ore",
  }),
  prefab: Object.freeze({
    AdvancedResearchCenter: "Super Computer",
    AirFilter: "Deodorizer",
    Algae: "Algae",
    BasicForagePlantPlanted: "Buried Muckroot",
    BasicPlantFood: "Meal Lice",
    BasicSingleHarvestPlant: "Mealwood",
    Battery: "Battery",
    BatteryMedium: "Jumbo Battery",
    BatterySmart: "Smart Battery",
    Bed: "Cot",
    BleachStone: "Bleach Stone",
    BottleEmptier: "Bottle Emptier",
    CO2Scrubber: "Carbon Skimmer",
    Canvas: "Blank Canvas",
    Carbon: "Coal",
    CeilingLight: "Ceiling Light",
    Checkpoint: "Duplicant Checkpoint",
    Clay: "Clay",
    ColdBreather: "Wheezewort",
    ColdWheat: "Sleet Wheat",
    ColdWheatSeed: "Sleet Wheat Grain",
    Compost: "Compost",
    CookingStation: "Electric Grill",
    CreatureDeliveryPoint: "Critter Drop-Off",
    CreatureFeeder: "Critter Feeder",
    DiningTable: "Mess Table",
    Dirt: "Dirt",
    DirtyIce: "Polluted Ice",
    DirtyWater: "Polluted Water",
    Door: "Pneumatic Door",
    Drecko: "Drecko",
    DreckoEgg: "Drecko Egg",
    EggIncubator: "Incubator",
    Electrolyzer: "Electrolyzer",
    ExteriorWall: "Drywall",
    FacilityBackWallWindow: "Window",
    FarmTile: "Farm Tile",
    FertilizerMaker: "Fertilizer Synthesizer",
    FirePole: "Fire Pole",
    FloorSwitch: "Weight Plate",
    FlowerVase: "Flower Pot",
    FlushToilet: "Lavatory",
    GasConduit: "Gas Pipe",
    GasConduitBridge: "Gas Bridge",
    GasConduitRadiant: "Radiant Gas Pipe",
    GasFilter: "Gas Filter",
    GasLogicValve: "Gas Shutoff",
    GasPermeableMembrane: "Airflow Tile",
    GasPump: "Gas Pump",
    GasVent: "Gas Vent",
    GasVentHighPressure: "High Pressure Gas Vent",
    GeneShuffler: "Neural Vacillator",
    Generator: "Coal Generator",
    GeyserGeneric_big_volcano: "Volcano",
    GeyserGeneric_chlorine_gas: "Chlorine Gas Vent",
    GeyserGeneric_chlorine_gas_cool: "Cool Chlorine Gas Vent",
    GeyserGeneric_filthy_water: "Polluted Water Vent",
    GeyserGeneric_hot_co2: "Carbon Dioxide Vent",
    GeyserGeneric_hot_hydrogen: "Hydrogen Vent",
    GeyserGeneric_hot_po2: "Hot Polluted Oxygen Vent",
    GeyserGeneric_hot_steam: "Steam Vent",
    GeyserGeneric_hot_water: "Water Geyser",
    GeyserGeneric_liquid_co2: "Carbon Dioxide Geyser",
    GeyserGeneric_liquid_sulfur: "Liquid Sulfur Geyser",
    GeyserGeneric_methane: "Natural Gas Geyser",
    GeyserGeneric_molten_aluminum: "Aluminum Volcano",
    GeyserGeneric_molten_cobalt: "Cobalt Volcano",
    GeyserGeneric_molten_copper: "Copper Volcano",
    GeyserGeneric_molten_gold: "Gold Volcano",
    GeyserGeneric_molten_iron: "Iron Volcano",
    GeyserGeneric_molten_niobium: "Niobium Volcano",
    GeyserGeneric_molten_tungsten: "Tungsten Volcano",
    GeyserGeneric_murky_brine: "Polluted Brine Vent",
    GeyserGeneric_oil_drip: "Leaky Oil Fissure",
    GeyserGeneric_salt_water: "Salt Water Geyser",
    GeyserGeneric_slimy_po2: "Infectious Polluted Oxygen Vent",
    GeyserGeneric_slush_salt_water: "Cool Salt Slush Geyser",
    GeyserGeneric_slush_water: "Cool Slush Geyser",
    GeyserGeneric_small_volcano: "Minor Volcano",
    GeyserGeneric_steam: "Cool Steam Vent",
    Glom: "Morb",
    GoldAmalgam: "Gold Amalgam",
    Granite: "Granite",
    Hatch: "Hatch",
    HatchEgg: "Hatch Egg",
    Headquarters: "Printing Pod",
    HighWattageWire: "Heavi-Watt Wire",
    HydrogenGenerator: "Hydrogen Generator",
    HydroponicFarm: "Hydroponic Farm",
    Ice: "Ice",
    IgneousRock: "Igneous Rock",
    InsulatedGasConduit: "Insulated Gas Pipe",
    InsulatedLiquidConduit: "Insulated Liquid Pipe",
    InsulationTile: "Insulated Tile",
    Iron: "Iron",
    IronOre: "Iron Ore",
    Katairite: "Abyssalite",
    Ladder: "Ladder",
    LightBug: "Shine Bug",
    LiquidConditioner: "Thermo Aquatuner",
    LiquidConduit: "Liquid Pipe",
    LiquidConduitBridge: "Liquid Bridge",
    LiquidConduitRadiant: "Radiant Liquid Pipe",
    LiquidHeater: "Liquid Tepidizer",
    LiquidLogicValve: "Liquid Shutoff",
    LiquidPump: "Liquid Pump",
    LiquidPumpingStation: "Pitcher Pump",
    LiquidValve: "Liquid Valve",
    LiquidVent: "Liquid Vent",
    LogicGateAND: "AND Gate",
    LogicGateNOT: "NOT Gate",
    LogicGateXOR: "XOR Gate",
    LogicPressureSensorGas: "Atmo Sensor",
    LogicPressureSensorLiquid: "Hydro Sensor",
    LogicSwitch: "Signal Switch",
    LogicTemperatureSensor: "Thermo Sensor",
    LogicWire: "Automation Wire",
    LogicWireBridge: "Automation Wire Bridge",
    MaficRock: "Mafic Rock",
    ManualGenerator: "Manual Generator",
    ManualPressureDoor: "Manual Airlock",
    MassageTable: "Massage Table",
    MassiveHeatSink: "Anti Entropy Thermo-Nullifier",
    Meat: "Meat",
    MedicalCot: "Triage Cot",
    MeshTile: "Mesh Tile",
    MetalRefinery: "Metal Refinery",
    MetalTile: "Metal Tile",
    MethaneGenerator: "Natural Gas Generator",
    MicrobeMusher: "Microbe Musher",
    MineralDeoxidizer: "Oxygen Diffuser",
    Mushroom: "Mushroom",
    MushroomPlant: "Dusk Cap",
    Obsidian: "Obsidian",
    OilRefinery: "Oil Refinery",
    Oilfloater: "Slickster",
    OxyRock: "Oxylite",
    POIBunkerExteriorDoor: "Security Door",
    POIDoorInternal: "Security Door",
    POIFacilityDoor: "Lobby Doors",
    Pacu: "Pacu",
    PacuEgg: "Pacu Egg",
    PetroleumGenerator: "Petroleum Generator",
    Phosphorite: "Phosphorite",
    Polymerizer: "Polymer Press",
    PowerControlStation: "Power Control Station",
    PowerTransformer: "Large Power Transformer",
    PressureDoor: "Mechanized Airlock",
    PrickleFlower: "Bristle Blossom",
    PrickleGrass: "Bluff Briar",
    PropDesk: "Computer Desk",
    PropElevator: "Broken Elevator",
    PropFacilityChair: "Lobby Chair",
    PropFacilityChandelier: "Chandelier",
    PropFacilityCouch: "Lobby Couch",
    PropFacilityDesk: "Director's Desk",
    PropFacilityDisplay2: "Electronic Display",
    PropFacilityDisplay3: "Electronic Display",
    PropFacilityGlobeDroors: "Filing Cabinet",
    PropFacilityPainting: "Landscape Portrait",
    PropFacilityStatue: "Gravitas Monument",
    PropFacilityTable: "Coffee Table",
    PropFacilityWallDegree: "Doctorate Degree",
    PropLadder: "Ladder",
    PropLight: "Light Fixture",
    PropReceptionDesk: "Reception Desk",
    PropTable: "Table",
    PropTallPlant: "Potted Plant",
    Puft: "Puft",
    PuftEgg: "Puft Egg",
    RanchStation: "Grooming Station",
    RationBox: "Ration Box",
    Refrigerator: "Refrigerator",
    Regolith: "Regolith",
    ResearchCenter: "Research Station",
    RockCrusher: "Rock Crusher",
    RoleStation: "Skills Board",
    RotPile: "Rot Pile",
    SandStone: "Sandstone",
    Sculpture: "Large Sculpting Block",
    SedimentaryRock: "Sedimentary Rock",
    SetLocker: "Locker",
    SlimeMold: "Slime",
    Snow: "Snow",
    SolidCarbonDioxide: "Solid Carbon Dioxide",
    SolidConduit: "Conveyor Rail",
    SolidConduitBridge: "Conveyor Bridge",
    SolidConduitInbox: "Conveyor Loader",
    SolidConduitOutbox: "Conveyor Receptacle",
    SolidTransferArm: "Auto-Sweeper",
    SpiceNut: "Pincha Peppernut",
    StorageLocker: "Storage Bin",
    StorageLockerSmart: "Smart Storage Bin",
    SuitFabricator: "Exosuit Forge",
    SuitLocker: "Atmo Suit Dock",
    SuitMarker: "Atmo Suit Checkpoint",
    SwampLily: "Balm Lily",
    SwampLilyFlower: "Balm Lily Flower",
    ThermalBlock: "Tempshift Plate",
    Tile: "Tile",
    TilePOI: "Tile",
    ToxicSand: "Polluted Dirt",
    VendingMachine: "Vending Machine",
    WashBasin: "Wash Basin",
    WashSink: "Sink",
    Water: "Water",
    WaterPurifier: "Water Sieve",
    Wire: "Wire",
    WireBridge: "Wire Bridge",
    WireBridgeHighWattage: "Heavi-Watt Joint Plate",
    WireRefined: "Conductive Wire",
    WireRefinedHighWattage: "Heavi-Watt Conductive Wire",
  }),
  attribute: Object.freeze({
    Art: "Creativity",
    Athletics: "Athletics",
    Botanist: "Agriculture",
    Caring: "Medicine",
    Construction: "Construction",
    Cooking: "Cuisine",
    Digging: "Excavation",
    Learning: "Science",
    Machinery: "Machinery",
    Ranching: "Husbandry",
    SpaceNavigation: "Piloting",
    Strength: "Strength",
  }),
  skill: Object.freeze({
    Arting1: "Art Fundamentals",
    Arting2: "Aesthetic Design",
    Arting3: "Masterworks",
    Astronomy: "Astronomy",
    AtomicResearch: "Applied Sciences Research",
    Basekeeping1: "Improved Strength",
    Basekeeping2: "Plumbing",
    BionicsA1: "Booster Processing I",
    BionicsA2: "Booster Processing II",
    BionicsA3: "Complex Processing",
    BionicsB1: "Improved Gears I",
    BionicsB2: "Improved Gears II",
    BionicsC1: "Schematics",
    BionicsC2: "Advanced Schematics",
    BionicsC3: "Power Banking",
    BionicsD1: "Improved Hardware",
    BionicsD2: "Climate Control",
    Building1: "Improved Construction I",
    Building2: "Improved Construction II",
    Building3: "Demolition",
    Cooking1: "Grilling",
    Cooking2: "Enhanced Seasoning",
    Cooking3: "Fine Dining",
    Engineering1: "Mechatronics Engineering",
    Farming1: "Improved Farming I",
    Farming2: "Crop Tending",
    Farming3: "Improved Farming II",
    Hauling1: "Improved Carrying I",
    Hauling2: "Improved Carrying II",
    Medicine1: "Medicine Compounding",
    Medicine2: "Bedside Manner",
    Medicine3: "Advanced Medical Care",
    Mining1: "Hard Digging",
    Mining2: "Superhard Digging",
    Mining3: "Super-Duperhard Digging",
    Mining4: "Hazmat Digging",
    Pyrotechnics: "Pyrotechnics",
    Ranching1: "Critter Ranching I",
    Ranching2: "Critter Ranching II",
    Researching1: "Advanced Research",
    Researching2: "Field Research",
    Researching3: "Astronomy",
    Researching4: "Applied Sciences Research",
    RocketPiloting1: "Rocket Piloting",
    RocketPiloting2: "Rocket Piloting II",
    SpaceResearch: "Data Analysis Researcher",
    Suits1: "Exosuit Training",
    Swimming: "Basic Swimming",
    Swimming2: "Divemaster",
    Technicals1: "Improved Tinkering",
    Technicals2: "Electrical Engineering",
    ThermalSuits: "Suit Sustainability Training",
  }),
  skillGroup: Object.freeze({
    Art: "Decorating",
    Basekeeping: "Tidying",
    Building: "Building",
    Cooking: "Cooking",
    Farming: "Farming",
    Hauling: "Supplying",
    MedicalAid: "Doctoring",
    Mining: "Digging",
    Ranching: "Ranching",
    Research: "Researching",
    Rocketry: "Rocketry",
    Suits: "Suit Wearing",
    SwimmingSkills: "Swimming",
    Technicals: "Operating",
  }),
  trait: Object.freeze({
    Aggressive: "Destructive",
    Allergies: "Allergies",
    Anemic: "Anemic",
    Archaeologist: "Relic Hunter",
    BalloonArtist: "Balloon Artist",
    BedsideManner: "Caregiver",
    BingeEater: "Binge Eater",
    CalorieBurner: "Bottomless Stomach",
    CantBuild: "Unconstructive",
    CantCook: "Gastrophobia",
    CantDig: "Trypophobia",
    CantResearch: "Yokel",
    DeeperDiversLungs: "Deep Diver's Lungs",
    DiversLung: "Diver's Lungs",
    EarlyBird: "Early Bird",
    FastLearner: "Quick Learner",
    Flatulence: "Flatulent",
    Foodie: "Gourmet",
    Greasemonkey: "Grease Monkey",
    Hemophobia: "Squeamish",
    InteriorDecorator: "Interior Decorator",
    IronGut: "Iron Gut",
    IrritableBowel: "Irritable Bowel",
    MoleHands: "Mole Hands",
    MouthBreather: "Mouth Breather",
    Narcolepsy: "Narcoleptic",
    NightOwl: "Night Owl",
    NoodleArms: "Noodle Arms",
    Regeneration: "Regenerative",
    RockCrusher: "Beefsteak",
    ScaredyCat: "Pacifist",
    SimpleTastes: "Shrivelled Tastebuds",
    SlowLearner: "Slow Learner",
    SmallBladder: "Small Bladder",
    Snorer: "Loud Sleeper",
    SparkleStreaker: "Sparkle Streaker",
    StickerBomber: "Sticker Bomber",
    StressVomiter: "Vomiter",
    StrongArm: "Buff",
    StrongImmuneSystem: "Germ Resistant",
    SunnyDisposition: "Sunny Disposition",
    SuperProductive: "Super Productive",
    Twinkletoes: "Twinkletoes",
    UglyCrier: "Ugly Crier",
    Uncultured: "Uncultured",
    WeakImmuneSystem: "Biohazardous",
  }),
  geyser: Object.freeze({
    big_volcano: "Volcano",
    chlorine_gas: "Chlorine Gas Vent",
    chlorine_gas_cool: "Cool Chlorine Gas Vent",
    filthy_water: "Polluted Water Vent",
    hot_co2: "Carbon Dioxide Vent",
    hot_hydrogen: "Hydrogen Vent",
    hot_po2: "Hot Polluted Oxygen Vent",
    hot_steam: "Steam Vent",
    hot_water: "Water Geyser",
    liquid_co2: "Carbon Dioxide Geyser",
    liquid_sulfur: "Liquid Sulfur Geyser",
    methane: "Natural Gas Geyser",
    molten_aluminum: "Aluminum Volcano",
    molten_cobalt: "Cobalt Volcano",
    molten_copper: "Copper Volcano",
    molten_gold: "Gold Volcano",
    molten_iron: "Iron Volcano",
    molten_niobium: "Niobium Volcano",
    molten_tungsten: "Tungsten Volcano",
    murky_brine: "Polluted Brine Vent",
    oil_drip: "Leaky Oil Fissure",
    salt_water: "Salt Water Geyser",
    slimy_po2: "Infectious Polluted Oxygen Vent",
    slush_salt_water: "Cool Salt Slush Geyser",
    slush_water: "Cool Slush Geyser",
    small_volcano: "Minor Volcano",
    steam: "Cool Steam Vent",
  }),
  disease: Object.freeze({
    FoodPoisoning: "Food Poisoning",
    PollenGerms: "Floral Scent",
    RadiationSickness: "Radioactive Contaminants",
    SlimeLung: "Slimelung",
    ZombieSpores: "Zombie Spores",
  }),
  healthState: Object.freeze({
    Alright: "None",
    Critical: "Severe",
    Dead: "Conclusive",
    Incapacitated: "Paralyzing",
    Injured: "Moderate",
    Perfect: "None",
    Scuffed: "Minor",
  }),
});
